### ISSUE TITLE
LDA model object is not serializable

### ISSUE THREAD

**Issue by bmabey** [datamicroscopes/lda#7]
The `microscopes.lda._model.state` can not be serialized to disk via `cPickle`. You are probably aware of this due to the cython/c++ implementation. Are there plans to support this in the future or do you suggest another way to [de]serialize trained models?

**Comment by tdhopper** [comment]
@bmabey: Let me look into this. I think @stephentu came up with a way to handle it for mixture model and irm.

**Comment by tdhopper** [comment]
@bmabey This is fixed as of [0.4.0](https://github.com/datamicroscopes/lda/tree/0.4.0) which is currently the version you get with conda. Test for pickling [is here](https://github.com/datamicroscopes/lda/blob/ea9d883e2927189a8ec880e6f4ee49bc699dcfad/test/test_state.py#L41-L56).

**Comment by bmabey** [comment]
@tdhopper Great, thanks for this!

**Comment by tdhopper** [comment]
@bmabey found an occasional bug, but it is fixed in 0.4.1
